/**
 * LLM judgment module (§8.5).
 *
 * Provides sector-level information assessment for medium-confidence signals.
 * Two providers:
 *   - mock: deterministic responses for testing / offline use
 *   - openrouter: real LLM via OpenRouter API
 *
 * Environment variables:
 *   LLM_PROVIDER     — "mock" (default) or "openrouter"
 *   OPENROUTER_API_KEY — required when provider is "openrouter"
 *   OPENROUTER_MODEL   — model ID (default: "anthropic/claude-sonnet-4")
 */

import { JP_SECTOR_NAMES } from "./config.js";

/** §8.5.5 judgment categories */
export type LLMJudgment = "tailwind" | "neutral" | "headwind" | "invalid";

/** §8.5.6 structured output */
export type LLMResult = {
  judgment: LLMJudgment;
  summary: string;
  sectorNotes: Record<string, string>;
  confidence: number;
  provider: string;
  model: string;
  rawResponse?: string;
};

export type LLMInput = {
  date: string;
  signalRange: number;
  band: "medium";
  longCandidates: string[];
  shortCandidates: string[];
  signals: Record<string, number>;
  newsContext?: string;
  marketContext?: string;
};

type LLMProvider = {
  judge(input: LLMInput): Promise<LLMResult>;
};

function buildPrompt(input: LLMInput): string {
  const longDesc = input.longCandidates
    .map((t) => `  ${t} (${JP_SECTOR_NAMES[t] ?? t}): signal=${input.signals[t]?.toFixed(4)}`)
    .join("\n");
  const shortDesc = input.shortCandidates
    .map((t) => `  ${t} (${JP_SECTOR_NAMES[t] ?? t}): signal=${input.signals[t]?.toFixed(4)}`)
    .join("\n");

  const newsSection = input.newsContext
    ? `\n## Recent Market News (last 24h)\n${input.newsContext}\n`
    : "\n## Recent Market News\n(No news data available — use your general knowledge)\n";

  const marketSection = input.marketContext
    ? `\n## US Market Indicators (overnight)\n${input.marketContext}\n`
    : "";

  return `You are a quantitative trading analyst reviewing a sector rotation signal for Japanese equity ETFs.

## Context
- Date: ${input.date}
- Signal Range: ${input.signalRange.toFixed(4)} (medium confidence band)
- This signal was generated by a US-Japan sector lead-lag model (PCA_SUB).
- US sector movements from the previous session predict JP sector movements for today.

## Signal Candidates
Long (expected to outperform):
${longDesc}

Short (expected to underperform):
${shortDesc}
${marketSection}${newsSection}
## Your Task
Assess whether current market conditions support this sector rotation signal.
Consider:
1. Are there major events (earnings, policy, geopolitical) that could override the statistical signal?
2. Is the sector allocation consistent with current macro themes?
3. Any sector-specific risks (regulatory, structural) that the model might miss?
4. Does the recent news support or contradict the signal direction?

## Required Output (JSON only)
{
  "judgment": "tailwind" | "neutral" | "headwind" | "invalid",
  "summary": "1-2 sentence assessment",
  "sectorNotes": { "ticker": "brief note for relevant sectors" },
  "confidence": 0.0-1.0
}

Rules:
- "tailwind": conditions support the signal → trade at normal size
- "neutral": no strong reason to override → trade at half size
- "headwind": conditions work against the signal → skip trade
- "invalid": data quality or structural issue → skip trade
- NEVER override a high-confidence signal (this only runs for medium band)

Respond with ONLY the JSON object, no other text.`;
}

function createMockProvider(): LLMProvider {
  return {
    async judge(input: LLMInput): Promise<LLMResult> {
      // Deterministic mock: base judgment on signal range magnitude
      // Higher range → more likely tailwind, lower → neutral
      const range = input.signalRange;
      let judgment: LLMJudgment;
      let summary: string;
      let confidence: number;

      if (range > 0.15) {
        judgment = "tailwind";
        summary = "Signal range is moderately strong within medium band. No conflicting macro themes detected.";
        confidence = 0.7;
      } else if (range > 0.08) {
        judgment = "neutral";
        summary = "Signal range is moderate. No strong directional bias from macro conditions.";
        confidence = 0.5;
      } else {
        judgment = "headwind";
        summary = "Signal range is weak within medium band. Insufficient conviction for execution.";
        confidence = 0.3;
      }

      const sectorNotes: Record<string, string> = {};
      for (const t of [...input.longCandidates, ...input.shortCandidates]) {
        sectorNotes[t] = `${JP_SECTOR_NAMES[t] ?? t}: mock assessment — no specific risks identified`;
      }

      return {
        judgment,
        summary,
        sectorNotes,
        confidence,
        provider: "mock",
        model: "mock-v1",
      };
    },
  };
}

function createOpenRouterProvider(): LLMProvider {
  const apiKey = process.env.OPENROUTER_API_KEY;
  if (!apiKey) throw new Error("OPENROUTER_API_KEY is required when LLM_PROVIDER=openrouter");
  const model = process.env.OPENROUTER_MODEL ?? "anthropic/claude-sonnet-4";

  return {
    async judge(input: LLMInput): Promise<LLMResult> {
      const prompt = buildPrompt(input);

      const res = await fetch("https://openrouter.ai/api/v1/chat/completions", {
        method: "POST",
        headers: {
          "Authorization": `Bearer ${apiKey}`,
          "Content-Type": "application/json",
          "HTTP-Referer": "https://github.com/turtle-gate",
          "X-Title": "turtle-gate",
        },
        body: JSON.stringify({
          model,
          messages: [{ role: "user", content: prompt }],
          temperature: 0.1,
          max_tokens: 1024,
        }),
      });

      if (!res.ok) {
        const body = await res.text();
        throw new Error(`OpenRouter API error ${res.status}: ${body}`);
      }

      const data = await res.json() as {
        choices: { message: { content: string } }[];
      };
      const raw = data.choices?.[0]?.message?.content ?? "";

      // Parse JSON from response (handle markdown code blocks)
      const jsonMatch = raw.match(/\{[\s\S]*\}/);
      if (!jsonMatch) {
        return {
          judgment: "invalid",
          summary: "Failed to parse LLM response as JSON",
          sectorNotes: {},
          confidence: 0,
          provider: "openrouter",
          model,
          rawResponse: raw,
        };
      }

      try {
        const parsed = JSON.parse(jsonMatch[0]) as {
          judgment?: string;
          summary?: string;
          sectorNotes?: Record<string, string>;
          confidence?: number;
        };

        const validJudgments: LLMJudgment[] = ["tailwind", "neutral", "headwind", "invalid"];
        const judgment = validJudgments.includes(parsed.judgment as LLMJudgment)
          ? (parsed.judgment as LLMJudgment)
          : "invalid";

        return {
          judgment,
          summary: parsed.summary ?? "",
          sectorNotes: parsed.sectorNotes ?? {},
          confidence: typeof parsed.confidence === "number" ? parsed.confidence : 0,
          provider: "openrouter",
          model,
          rawResponse: raw,
        };
      } catch {
        return {
          judgment: "invalid",
          summary: "Failed to parse LLM JSON output",
          sectorNotes: {},
          confidence: 0,
          provider: "openrouter",
          model,
          rawResponse: raw,
        };
      }
    },
  };
}

let cachedProvider: LLMProvider | null = null;

function getProvider(): LLMProvider {
  if (cachedProvider) return cachedProvider;
  const name = process.env.LLM_PROVIDER ?? "mock";
  cachedProvider = name === "openrouter" ? createOpenRouterProvider() : createMockProvider();
  return cachedProvider;
}

/** Run LLM judgment for a medium-confidence signal (§8.5). */
export async function judgeMediumBand(input: LLMInput): Promise<LLMResult> {
  return getProvider().judge(input);
}

/** Reset provider cache (for testing). */
export function resetProvider(): void {
  cachedProvider = null;
}
